
{
    # JSON っぽい書き方をした YAML
    # 全般の設定
    'general': {

        # 利用するバックエンド
        # Mirakurun・EDCB から選択
        'backend': 'EDCB',

        # Mirakurun の HTTP API の URL
        # バックエンドに Mirakurun を選択した場合に利用される
        'mirakurun_url': 'http://192.168.1.11:40772/',

        # EDCB (EpgTimerNW) の TCP API の URL
        # バックエンドに EDCB を選択した場合に利用される
        # tcp://edcb-namedpipe/ と指定すると、TCP API の代わりに名前付きパイプで通信を行う (ローカルのみ)
        'edcb_url': 'tcp://192.168.1.11:4510/',

        # デバッグモードを有効にするか
        # 有効にした場合、表示されるログが増える
        'debug': True,
    },

    # Web サーバーの設定
    'server': {

        # KonomiTV サーバーのリッスンポート
        # デフォルトは 7000
        'port': 7000,
    },

    # テレビのライブストリーミングの設定
    'tv': {

        # 利用するエンコーダー
        # FFmpeg・QSVEncC・NVEncC・VCEEncC から選択
        'encoder': 'QSVEncC',

        # 誰も見ていないライブストリームを何秒まで維持するか
        # 10 秒に設定したなら、10 秒間誰も見ていない状態が継続したらライブストリーム（エンコーダー）を終了する
        # 0 秒に設定するとリロードしただけでチューナーオープンとエンコードがやり直しになってしまうため、余裕をもたせておく事を推奨
        'max_alive_time': 10,

        # デバッグ用に再生する TS ファイルの絶対パス（デバッグ用設定のため、変更は推奨しない）
        # この値に TS ファイルのパスを指定すると、すべてのチャンネルにおいて、ストリーミングされる映像（字幕・文字スーパーを含む）が
        # リアルタイムで放送されているものから強制的に指定した TS ファイルのものに置き換えられる
        # 開発者がライブストリーム関連の機能をテストするために使う特殊な設定
        'debug_mode_ts_path': null,
    },

    # キャプチャの設定
    'capture': {

        # アップロードしたキャプチャ画像を保存するフォルダの絶対パス
        # クライアントの [キャプチャの保存先] 設定で [KonomiTV サーバーにアップロード] または
        # [ブラウザでのダウンロードと、KonomiTV サーバーへのアップロードを両方行う] を選択した場合に利用される
        # Docker でインストールした場合もホストマシン側のフォルダパスを指定すること
        'upload_folder': 'E:\TV-Capture',
    },
}
