
{
    # JSON っぽい書き方をした YAML
    # 全般の設定
    'general': {

        # デバッグモードを有効にするか
        # 有効にした場合、表示されるログが増える
        'debug': True,

        # Mirakurun の URL
        'mirakurun_url': 'http://192.168.1.11:40772',
    },

    # ライブストリームの設定
    'livestream': {

        # 優先して利用するエンコーダー
        # FFmpeg・QSVEncC・NVEncC・VCEEncC から選択
        'preferred_encoder': 'QSVEncC',

        # 優先して利用する画質
        # 1080p・720p・540p・480p・360p・240p から選択
        'preferred_quality': '1080p',

        # 誰も見ていないライブストリームを何秒まで維持するか
        # 10 秒に設定したなら、10 秒間誰も見ていない状態が継続したらライブストリーム（エンコーダー）を終了する
        # 0 秒に設定するとリロードしただけでチューナーオープンとエンコードがやり直しになってしまうため、余裕をもたせておく事を推奨
        'max_alive_time': 10,
    }
}
