
version: '3'
services:
    konomitv:
        image: konomitv
        container_name: KonomiTV
        restart: always
        build:
            context: .
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [compute, utility, video]
        devices:
            - '/dev/dri:/dev/dri'
        volumes:
            - type: bind
              source: './config.yaml'
              target: '/code/config.yaml'
            - type: bind
              source: './client/'
              target: '/code/client/'
            - type: bind
              source: './server/app/'
              target: '/code/server/app/'
            - type: bind
              source: './server/data/'
              target: '/code/server/data/'
            - type: bind
              source: './server/static/'
              target: '/code/server/static/'
        ports:
            - '7000:7000'
