[tool.poetry]
name = "KonomiTV-Installer"
version = "0.8.0-dev"
description = "KonomiTV Installer"
authors = ["tsukumi <tsukumijima@users.noreply.github.com>"]

[tool.taskipy.tasks]
dev = "python KonomiTV-Installer.py"
build-windows = "pyinstaller --onefile --uac-admin --icon=KonomiTV-Installer.ico KonomiTV-Installer.py"
build-linux = "pyinstaller --onefile --name=KonomiTV-Installer.elf KonomiTV-Installer.py"

[tool.poetry.dependencies]
python = "3.11.*"
aiofiles = "^23.2.1"
distro = "^1.8.0"
elevate = "^0.1.3"
emoji = "^2.8.0"
ifaddr = "^0.2.0"
psutil = "^5.9.5"
py7zr = "^0.20.6"
# For the Windows version only, to prevent virus detection, when the installer is built by CI,
# it is forced to replace the PyInstaller with my own build.
# When updating PyInstaller, all versions listed in the tsukumijima/Pyinstaller-Builds/.github/workflows/build.yml
# and in KonomiTV/.github/workflows/build_installer.yaml must be updated.
# ref: https://github.com/tsukumijima/Pyinstaller-Builds/blob/master/.github/workflows/build.yml
pyinstaller = "==5.13.0"
requests = "^2.31.0"
rich = "^13.5.3"
"ruamel.yaml" = "^0.17.32"
taskipy = "^1.12.0"
watchdog = "^3.0.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
